# Generated by Django 3.2.3 on 2021-05-15 00:08

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField()),
                ('shortcut', models.CharField(blank=True, default=core.utils.random_shortcut, max_length=30, unique=True)),
            ],
        ),
    ]
